// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_iMEia8-wzU7Pj7c7RG-6b-BC_9tUUUQ',
    appId: '1:987872169819:web:6b9dcaa8f3ebe02ca4547e',
    messagingSenderId: '987872169819',
    projectId: 'smartbagg-49683',
    authDomain: 'smartbagg-49683.firebaseapp.com',
    storageBucket: 'smartbagg-49683.firebasestorage.app',
    measurementId: 'G-Q7TFTRE5S7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJl7xWNT1Yg6694Gwy5J7TuvtbCBAJaYs',
    appId: '1:987872169819:android:b92a7455c2420a85a4547e',
    messagingSenderId: '987872169819',
    projectId: 'smartbagg-49683',
    storageBucket: 'smartbagg-49683.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANASBELyQBRnUC2zzR7Cgw0PVu8LP53C4',
    appId: '1:987872169819:ios:ee2183a1014c9a30a4547e',
    messagingSenderId: '987872169819',
    projectId: 'smartbagg-49683',
    storageBucket: 'smartbagg-49683.firebasestorage.app',
    iosClientId: '987872169819-7io3ooora6v2hkqi3fnuec5kvk8o0gm9.apps.googleusercontent.com',
    iosBundleId: 'com.example.smartbag2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyANASBELyQBRnUC2zzR7Cgw0PVu8LP53C4',
    appId: '1:987872169819:ios:ee2183a1014c9a30a4547e',
    messagingSenderId: '987872169819',
    projectId: 'smartbagg-49683',
    storageBucket: 'smartbagg-49683.firebasestorage.app',
    iosClientId: '987872169819-7io3ooora6v2hkqi3fnuec5kvk8o0gm9.apps.googleusercontent.com',
    iosBundleId: 'com.example.smartbag2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD_iMEia8-wzU7Pj7c7RG-6b-BC_9tUUUQ',
    appId: '1:987872169819:web:2e8d96d3b483c0cea4547e',
    messagingSenderId: '987872169819',
    projectId: 'smartbagg-49683',
    authDomain: 'smartbagg-49683.firebaseapp.com',
    storageBucket: 'smartbagg-49683.firebasestorage.app',
    measurementId: 'G-F09EKBR3EM',
  );
}
